stages:
  setup:
    cmd: bash setup.sh
    deps:
    - setup.sh
    - requirements.txt
  ingest:
    cmd: python ingest.py
    params:
    - TextSplitter
    deps:
    - data
    - ingest.py
    outs:
    - docs.json
    - metadatas.json
  vectorize:
    cmd: python vector_store.py
    params:
    - Embeddings
    deps:
    - docs.json
    - metadatas.json
    - vector_store.py
    outs:
    - docs.index
  run:
    cmd: python qa.py
    params:
    - Embeddings
    - ChatLLM
    - Retrieval
    deps:
    - docs.index
    - ground_truths.csv
    - qa.py
    outs:
    - results.json
  eval:
    cmd: python eval.py
    deps:
    - ground_truths.csv
    - results.json
    - eval.py
    outs:
    - eval.csv
  eval_ragas:
    cmd: python eval_ragas.py
    deps:
    - ground_truths.csv
    - results.json
    - eval_ragas.py
    outs:
    - eval_ragas.csv
