stages:
  ingest:
    cmd: python ingest.py
    params:
    - TextSplitter
    deps:
    - https://github.com/progit/progit2/releases/download/2.1.426/progit.pdf
    - ingest.py
    outs:
    - docs.json
  vectorize:
    cmd: python vector_store.py
    params:
    - Embeddings
    deps:
    - docs.json
    - vector_store.py
    outs:
    - docs.index
  run:
    cmd: python qa.py
    params:
    - Embeddings
    - ChatLLM
    deps:
    - docs.index
    - ground_truths.csv
    - qa.py
    outs:
    - results.json
  eval:
    cmd: python eval.py
    deps:
    - ground_truths.csv
    - results.json
    - eval.py
    outs:
    - eval.csv
  eval_ragas:
    cmd: python eval_ragas.py
    deps:
    - ground_truths.csv
    - results.json
    - eval_ragas.py
    outs:
    - eval_ragas.csv
