stages:
  ingest:
    cmd: python src/ingest.py
    deps:
    - dvc_discord_channel.csv
    - src/ingest.py
    outs:
    - docs.json
  vectorize:
    cmd: python src/vector_store.py
    params:
    - Embeddings
    deps:
    - docs.json
    - src/vector_store.py
    outs:
    - docs.index
  run:
    cmd: python src/qa_embeddings.py
    params:
    - Embeddings
    - ChatLLM
    deps:
    - docs.index
    - ground_truths_dvc.csv
    - src/qa.py
    outs:
    - results.json
  eval:
    cmd: python src/eval.py
    params:
    - Embeddings
    - ChatLLM
    deps:
    - ground_truths_dvc.csv
    - results.json
    - src/eval.py
    outs:
    - eval.csv
