stages:
  expand:
    cmd: bash expand_data.sh
    deps:
    - Export-d3adfe0f-3131-4bf3-8987-a52017fc1bae.zip
    - expand_data.sh
    outs:
    - Notion_DB
  ingest:
    cmd: python ingest.py
    deps:
    - Notion_DB
    - ingest.py
    outs:
    - docs.json
    - metadatas.json
  vectorize:
    cmd: python vector_store.py
    deps:
    - docs.json
    - metadatas.json
    - vector_store.py
    outs:
    - docs.index
    - faiss_store.pkl
  run:
    cmd: python qa.py
    deps:
    - docs.index
    - faiss_store.pkl
    - samples.txt
    - qa.py
    outs:
    - results.csv
