stages:
  ingest:
    cmd: python src/ingest.py
    params:
    - TextSplitter
    deps:
    - https://github.com/progit/progit2/releases/download/2.1.426/progit.pdf
    - src/ingest.py
    outs:
    - docs.json
  run:
    cmd: python src/qa.py
    params:
    - ChatLLM
    deps:
    - ground_truths.csv
    - src/qa.py
    outs:
    - results.json
  eval:
    cmd: python src/eval.py
    params:
    - Embeddings
    - ChatLLM
    deps:
    - ground_truths.csv
    - results.json
    - src/eval.py
    outs:
    - eval.csv
