TextSplitter:
  chunk_size: 1500
  chunk_overlap: 200
  keep_separator: False
  add_start_index: False
Embeddings:
  model_name: 'sentence-transformers/all-mpnet-base-v2'
  model_kwargs:
    device: cpu
  encode_kwargs:
    normalize_embeddings: true
    show_progress_bar: true
ChatLLM:
  repo_id: 'HuggingFaceH4/zephyr-7b-beta'
Retrieval:
  max_tokens_limit: 3375
  reduce_k_below_max_tokens: False
  verbose: True
Eval:
  repo_id: 'HuggingFaceH4/zephyr-7b-beta'
