TextSplitter:
  chunk_size: 1500
  chunk_overlap: 200
  keep_separator: False
  add_start_index: False
Embeddings:
  num_ctx: 8191
  model: 'llama2:7b'
  show_progress: true
Chat:
  model: 'llama2:7b'
Retrieval:
  max_tokens_limit: 3375
  reduce_k_below_max_tokens: False
  verbose: True
Eval:
  model: 'llama2:7b'
